# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: mixed-line-ending

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        additional_dependencies:
        - types-PyYAML>=6.0.0
        - boto3-stubs[s3]>=1.26.29

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
  #- repo: local
    #hooks:
      #- id: pylint
        #name: pylint
        #entry: pylint
        #language: system
        #types: [python]
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
      - id: isort
  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.7.3
    hooks:
      - id: pydocstringformatter
  - repo: https://github.com/crate-ci/typos
    rev: v1.13.6
    hooks:
      - id: typos
  #- repo: https://github.com/streetsidesoftware/cspell-cli
    #rev: v6.2.0
    #hooks:
      #- id: cspell
  #- repo: https://github.com/jendrikseipp/vulture
    #rev: 'v2.3'  # or any later Vulture version
    #hooks:
      #- id: vulture
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
      - id: markdownlint-fix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
