default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

default_stages:
  - commit
  - push

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending

  - repo: https://github.com/crate-ci/typos
    rev: v1.23.6
    hooks:
      - id: typos
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
      - id: markdownlint-fix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.0  # automatically updated by Commitizen
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - post-commit
          - push
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
